# Generated by Django 3.2.7 on 2021-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='item_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='item_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
