# Generated by Django 3.2.7 on 2021-11-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211108_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ManyToManyField(related_name='us_name', to='auctions.AuctionListing'),
        ),
    ]
