# Generated by Django 3.2.7 on 2021-11-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211108_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
