# Generated by Django 3.2.7 on 2021-11-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211108_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
