# Generated by Django 3.2.7 on 2021-11-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comments_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
