# Generated by Django 3.2.7 on 2021-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='item_number',
            field=models.IntegerField(default=0),
        ),
    ]
